### ISSUE TITLE
How to declare another Maven repository?

### ISSUE THREAD

**Issue by DjArt** [ikvm-revived/ikvm-maven#5]
Unfortunately, I did not find this point in the documentation. If this is not possible, please make it possible.

**Comment by wasabii** [comment]
The `MavenAdditionalRepositories` MSBuild property should be available to add additional repository specifications to. The format of this property is a series of semicolon separated values. Each value is in the following pattern: `{Id}={Url}`. The ID of the central repository is 'central' inline with standard Maven convention.

Authentication information is not supported within the MSBuild files. But because we internally use the Maven Aether library for resolution, standard `~/.m2/settings.xml` information should apply.

NuGet packages which rely on Maven packages do not include repository information, and thus it's inappropriate to publish a NuGet package that relies on artifacts outside of central on nuget.org.

**Comment by flour** [comment]
Hi, have a question on that
This way it should be correct?
```
    <ItemGroup>
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.4.1"/>

        <MavenReference Include="com.sumsub.sns:idensic-mobile-sdk" Version="1.23.1">
            <MavenAdditionalRepositories>sumsub=https://maven.sumsub.com/repository/maven-public/</MavenAdditionalRepositories>
        </MavenReference>
    </ItemGroup>
```
